name: login
on:
  workflow_dispatch:
 
jobs:
  deploy_pgadmin_intm:
    runs-on: [ubuntu-latest]
    environment: Test
    steps:
      - name: "Install azure-cli"
        uses: elstudio/action-install-azure-cli@v1
      - name: "Azure login"
        uses: azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
      
